apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  source:
    chart: datadog
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: datadog-secret
          appKeyExistingSecret: datadog-secret
          clusterName: "cheapaks"
        clusterAgent:
          metricsProvider:
            enabled: false
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
